services:
    information:
        image: ghcr.io/opengovernance-io/information-service:v0.420.0-dev
        container_name: information
        ports:
        - "8080:8080"
        environment:
          - INFORMATION_HTTP__ADDRESS=0.0.0.0:8080
          - INFORMATION_POSTGRES__HOST=postgres
          - INFORMATION_POSTGRES__PORT=5432
          - INFORMATION_POSTGRES__DB=information
          - INFORMATION_POSTGRES__USERNAME=information
          - INFORMATION_POSTGRES__PASSWORD=${PG_PASSWORD}
          - INFORMATION_POSTGRES_SSL_MODE=disable
        depends_on:
        - postgres
        networks:
        - kaytu-network
        restart: always
    postgres:
        image: postgres:14
        container_name: postgres
        volumes:
          - pgdata:/var/lib/postgresql/data
        environment:
        - POSTGRES_USER=information
        - POSTGRES_PASSWORD=${PG_PASSWORD}
        - POSTGRES_DB=information
        networks:
        - kaytu-network
        restart: always
volumes:
    pgdata:
        driver: local
        driver_opts:
          type: none
          device: "/home/ec2-user/information-service/pgdata"
          o: bind

networks:
    kaytu-network:
        driver: bridge