services:
    information:
        build: .
        container_name: information
        ports:
        - "8080:8080"
        environment:
          - INFORMATION_HTTP__ADDRESS=0.0.0.0:8080
          - INFORMATION_POSTGRES__HOST=postgres-uasage
          - INFORMATION_POSTGRES__PORT=5432
          - INFORMATION_POSTGRES__DB=information
          - INFORMATION_POSTGRES__USERNAME=information
          - INFORMATION_POSTGRES__PASSWORD=${PG_PASSWORD}
          - INFORMATION_POSTGRES_SSL_MODE=disable
        depends_on:
        - postgres-uasage
        networks:
        - og-network1
        restart: always
    postgres-uasage:
        image: postgres:latest
        container_name: postgres-usage
        volumes:
          - pgdata-usage:/var/lib/postgresql/data
        environment:
        - POSTGRES_USER=information
        - POSTGRES_PASSWORD=${PG_PASSWORD}
        - POSTGRES_DB=information
        networks:
        - og-network1
        restart: always
volumes:
    pgdata-usage:
       

networks:
    og-network1:
        driver: bridge